# -*- coding: utf-8 -*-
"""supply_chain_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOZ5oDCbTGutCVZT0cARzN9AW0Ydy7C0
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

df=pd.read_csv('/content/supply_chain_data.csv')
df.head()

df.shape,df.info()

df.describe()

"""# Data cleaning"""

df.isnull().sum().sum()
# No null value is present

df.duplicated().sum() # No duplicated value is present

df.columns

"""# EDA"""

# Select only categorical (object/string) columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

# Print unique values for each categorical column
for col in categorical_cols:
    print(f"Column: {col}")
    print(df[col].unique())

import plotly.express as px

# gives the mean of the defetct rates of each product
defect_rates_by_product = df.groupby('Product type')['Defect rates'].mean().reset_index()

fig = px.bar(
    defect_rates_by_product,
    x='Product type',
    y='Defect rates',

    title='Defect rates by Product type',
    text='Defect rates'     # 👈 ADD THIS LINE
)

color_scale=px.colors.qualitative.Pastel
fig.update_traces(marker_color=color_scale)
fig.update_traces(textposition='outside')  # 👈 to show text above bars
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')

fig.show()

"""* haircare has the highest defect rates with 2.48

* calculate and plot the risk score
"""

# supply chain risk assessment

risk_data=df[['SKU','Lead times','Stock levels']]
print(risk_data.head())

# risk score tells us how likely we are to run out of stock
risk_data['risk score'] = risk_data['Lead times'] + (1-risk_data.loc[:,'Stock levels'])
risk_data.head()

risk_data=risk_data.sort_values(by='risk score',ascending=False)[:30]
risk_data.head()

fig = px.bar(risk_data, x='SKU', y='risk score', title='Top 30 Highest-Risk Data',
             labels={'risk score': 'risk Score', 'SKU': 'SKU'},
             text='risk score')

color_scale=px.colors.qualitative.Set3
fig.update_traces(marker_color=color_scale)
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')

fig.show()

# positive value suggest the stockout risk , zero value: " Stock is jusr be enough " , negative: "have extra stock"

"""* EOQ (Economic Order Quality )
* EOQ tells how much quantity we should order at one time so that our ordering cost is low , holding cost is low and we nevwe run out of stock
"""

holdingcost=0.2

def calculate_eoq(data):

  S=data['Costs']
  D=data['Number of products sold']
  H=data['Number of products sold'] * holdingcost
  EOQ=np.sqrt((2*D*S)/H)
  return round(EOQ,2)

df['EOQ']=calculate_eoq(df)
df.head()

comparison_columns = df[['SKU', 'EOQ','Order quantities']]
comparison_columns.head()

# Extracting the top 10 rows for comparison
top_10_comparison = comparison_columns.head(10)

# Creating a bar plot to compare EOQ and Order Quantities for the top 10 SKUs
fig = px.bar(top_10_comparison, x='SKU', y=['EOQ', 'Order quantities'],
             title='Comparison of EOQ and Order Quantities for Top 10 SKUs')

fig.update_layout(
    title_x=0.5
)

# Displaying the plot
fig.show()

"""* CUSTOMER SEGMENTATION ANALYSIS"""

revenue_avg_by_demo_prod = df.groupby(['Customer demographics', 'Product type'])['Revenue generated'].mean().reset_index()
revenue_sum_by_demo_prod = df.groupby(['Customer demographics', 'Product type'])['Revenue generated'].sum().reset_index()

from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Create a palette of different colors for each product type
colors = px.colors.qualitative.Set3

# Create a subplot with 1 row and 2 columns
fig = make_subplots(rows=1, cols=2, subplot_titles=('Average Revenue', 'Total Revenue'))

# Plot for average revenue
for i, product_type in enumerate(revenue_avg_by_demo_prod['Product type'].unique()):
    subset = revenue_avg_by_demo_prod[revenue_avg_by_demo_prod['Product type'] == product_type]
    fig.add_trace(
        go.Bar(
            x=subset['Customer demographics'],
            y=subset['Revenue generated'],
            name=product_type,
            marker_color=colors[i]
        ),
        row=1, col=1
    )

# Plot for total revenue without legend
for i, product_type in enumerate(revenue_sum_by_demo_prod['Product type'].unique()):
    subset = revenue_sum_by_demo_prod[revenue_sum_by_demo_prod['Product type'] == product_type]
    fig.add_trace(
        go.Bar(
            x=subset['Customer demographics'],
            y=subset['Revenue generated'],
            showlegend=False,  # Hide legend for this subplot
            marker_color=colors[i]
        ),
        row=1, col=2
    )

# Beautify the subplot and show the legend for the first subplot
fig.update_layout(
    title='Revenue Analysis by Customer Demographics and Product Type',
    xaxis=dict(title='Customer Demographics'),
    yaxis=dict(title='Revenue'),
    xaxis2=dict(title='Customer Demographics'),
    yaxis2=dict(title='Revenue'),
    title_x=0.5,
    showlegend=True  # Show legend for the first subplot
)

# Show the subplot
fig.show()

"""* LEAD TIMES OPTIMIZATION ANALYSIS"""

avg_lead_times_transport = df.groupby(['Transportation modes'])['Lead times'].mean().reset_index()

fig = px.bar(avg_lead_times_transport, x='Transportation modes', y='Lead times',
             labels={'Transportation modes': 'Transportation Mode', 'Lead times': 'Average Lead Time'},
             title='Average Lead Times by Transportation Mode')

# Customize the color scale for bars
color_scale = px.colors.qualitative.Set3  # You can choose a different color scale
fig.update_traces(marker_color=color_scale)

# Customize the layout for beautification
fig.update_layout(
    title=dict(text='Average Lead Times by Transportation Mode', x=0.5),
    xaxis_title='Transportation Mode',
    yaxis_title='Average Lead Time',
    xaxis_tickangle=-45,  # Rotate x-axis labels for better readability
    font=dict(family="Arial", size=14),
    showlegend=False  # Remove legend
)

# Show the plot
fig.show()

best_transportation_mode = avg_lead_times_transport.loc[avg_lead_times_transport['Lead times'].idxmin()]
best_transportation_mode

best_transportation_data = df[df['Transportation modes']==best_transportation_mode['Transportation modes']]
best_transportation_data.head()

import plotly.express as px

avg_lead_times_route = df.groupby(['Routes'])['Lead times'].mean().reset_index()

# Assuming we have the avg_lead_times_route DataFrame already defined
fig = px.bar(avg_lead_times_route, x='Routes', y='Lead times',
             labels={'Routes': 'Route', 'Lead times': 'Average Lead Time'},
             title='Average Lead Times by Route')

# Customize the color scale for bars
color_scale = px.colors.qualitative.Set3
fig.update_traces(marker_color=color_scale)

fig.update_layout(
    title=dict(text='Average Lead Times by Route', x=0.5),
    xaxis_title='Route',
    yaxis_title='Average Lead Time',
    xaxis_tickangle=-45,
    font=dict(family="Arial", size=14),
    showlegend=False
)

fig.show()

best_route = avg_lead_times_route.loc[avg_lead_times_route['Lead times'].idxmin()]
best_route

best_route_data = df[df['Routes']==best_route['Routes']]
best_route_data.head()

"""* MODELLING"""

X = df.loc[:,['Price', 'Availability', 'Stock levels', 'Lead times', 'Order quantities']]
y = df.loc[:,'Number of products sold']

#num of folds for cross_validation
num_folds=10

# Initialize lists to store evaluation metrics
mse_scores = []
rmse_scores = []
mae_scores = []
r2_scores = []

from sklearn.model_selection import KFold

# Create a KFold object
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)

# Define the parameters for LightGBM
params = {
    'objective': 'regression',
    'metric': 'mean_squared_error',
    'boosting_type': 'gbdt',
    'num_leaves': 31,
    'learning_rate': 0.05,
    'feature_fraction': 0.9
}

import lightgbm as lgb
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Create LightGBM datasets for training and testing
    train_data = lgb.Dataset(X_train, label=y_train)
    test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)

    # Add early stopping
    num_round = 100  # Increase the number of boosting rounds
    early_stopping_rounds = 5  # Set the number of rounds to wait for early stopping

    # Train the model with early stopping
    bst = lgb.train(
        params,
        train_data,
        num_round,
        valid_sets=[test_data],
        callbacks=[lgb.early_stopping(stopping_rounds=early_stopping_rounds, verbose=False)]
    )

    # Make predictions on the test set
    y_pred = bst.predict(X_test, num_iteration=bst.best_iteration)

    # Calculate metrics
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Calculate the target range
    target_range = np.max(y_test) - np.min(y_test)

    # Calculate metrics as percentages
    percentage_mse = (mse / target_range) * 100
    percentage_rmse = (rmse / target_range) * 100
    percentage_mae = (mae / target_range) * 100
    percentage_r2 = (r2 * 100)

    # Append the scores to the respective lists
    mse_scores.append(percentage_mse)
    rmse_scores.append(percentage_rmse)
    mae_scores.append(percentage_mae)
    r2_scores.append(percentage_r2)

# Calculate the average scores over all folds
avg_mse = np.mean(mse_scores)
avg_rmse = np.mean(rmse_scores)
avg_mae = np.mean(mae_scores)
avg_r2 = np.mean(r2_scores)

# Print the results
print(f"Average Mean Squared Error: {avg_mse:.2f}%")
print(f"Average Root Mean Squared Error: {avg_rmse:.2f}%")
print(f"Average Mean Absolute Error: {avg_mae:.2f}%")
print(f"Average R-squared: {avg_r2:.2f}%")

"""* COST OPTIMIZATION"""

# Extract the features (X) and target (y)
X = df.loc[:, 'Production volumes'].values.reshape(-1, 1)
y = df.loc[:, 'Manufacturing costs'].values

# Define the number of folds for cross-validation
num_folds = 5

# Initialize lists to store evaluation metrics
mse_scores = []
rmse_scores = []
mae_scores = []
r2_scores = []

from sklearn.preprocessing import MinMaxScaler

# Initialize and fit the scaler to the data
scaler = MinMaxScaler()
scaler.fit(X)

# Create a KFold object
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)

import tensorflow as tf
from tensorflow.keras.layers import Dense, Input # Import Input layer
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Define Early Stopping callback (can be defined once outside the loop)
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Define Model Checkpoint callback (can be defined once outside the loop)
# The filepath for ModelCheckpoint needs to be unique if you want to save each fold's best model,
# or overwritten if you only care about the very best across all folds. For simplicity here,
# it will overwrite each time, saving the best from the *last* fold's training.
model_checkpoint = ModelCheckpoint('/kaggle/working/best_model.weights.h5', save_best_only=True, save_weights_only=True, monitor='val_loss', mode='min')

for i, (train_index, test_index) in enumerate(kf.split(X)): # Added enumerate to potentially use fold_idx for unique filepaths
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Scale the data
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Define and compile the neural network model inside the loop for each fold
    # This ensures a fresh model is trained for each fold of cross-validation.
    model = tf.keras.Sequential([
        Input(shape=(1,)), # Correct way to define input shape
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(1)
    ])

    model.compile(optimizer='adam', loss='mean_squared_error')

    # Train the model on the training data with callbacks
    history = model.fit(X_train_scaled,
                        y_train, epochs=100,
                        batch_size=32,
                        validation_data=(X_test_scaled, y_test),
                        callbacks=[early_stopping, model_checkpoint],
                        verbose=0) # Suppress verbose output to reduce log size

    # Load the best model weights from the saved checkpoint for evaluation
    model.load_weights('/kaggle/working/best_model.weights.h5')

    # Make predictions on the test set
    y_pred = model.predict(X_test_scaled).flatten() # Flatten y_pred to match y_test shape

    # Calculate metrics
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Calculate metrics as percentages
    target_range = np.max(y_test) - np.min(y_test)
    percentage_mse = (mse / target_range) * 100
    percentage_rmse = (rmse / target_range) * 100
    percentage_mae = (mae / target_range) * 100
    percentage_r2 = (r2 * 100)

    # Append the scores to the respective lists
    mse_scores.append(percentage_mse)
    rmse_scores.append(percentage_rmse)
    mae_scores.append(percentage_mae)
    r2_scores.append(percentage_r2)

# Calculate the average scores over all folds
avg_mse = np.mean(mse_scores)
avg_rmse = np.mean(rmse_scores)
avg_mae = np.mean(mae_scores)
avg_r2 = np.mean(r2_scores)

# Print the results
print("Neural Network Results")
print("----------------------")
print(f"Average Mean Squared Error: {avg_mse:.2f}%")
print(f"Average Root Mean Squared Error: {avg_rmse:.2f}%")
print(f"Average Mean Absolute Error: {avg_mae:.2f}%")
print(f"Average R-squared: {avg_r2:.2f}%")

from sklearn.ensemble import RandomForestRegressor
import numpy as np

# Find the most optimal production volume to minimize manufacturing cost
# X (Production volumes) and y (Manufacturing costs) are already defined from VsAM-AGbpbpU
# scaler is already fitted from o6zThL35pnN8

# Scale the training data (X) before training the model
X_scaled_for_training = scaler.transform(X) # X is the 'Production volumes' column

# Define and train the RandomForestRegressor model for cost prediction
model = RandomForestRegressor(n_estimators=100, random_state=42) # Initialize the model
model.fit(X_scaled_for_training, y) # Train the model on scaled X and y (Manufacturing costs)

min_production_volume = df['Production volumes'].min()
max_production_volume = 1000
step_size = 100

cheapest_cost = float('inf')
best_production_volume = None

for production_volume in range(min_production_volume, max_production_volume + 1, step_size):
    # Ensure the input to scaler.transform is 2D, as expected by the fitted scaler
    normalized_production_volume = scaler.transform(np.array([[production_volume]]))
    predicted_cost = model.predict(normalized_production_volume)

    # model.predict returns a 1D array for a single sample, so access with [0]
    if predicted_cost[0] < cheapest_cost:
        cheapest_cost = predicted_cost[0]
        best_production_volume = production_volume

print('Most optimal production volume to minimize manufacturing cost:', best_production_volume)
print('The cheapest manufacturing cost:', cheapest_cost)

